version: '3.8'

services:
  compliance-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_LOCATION=${GCP_LOCATION:-us-central1}
      - CONFLUENCE_BASE_URL=${CONFLUENCE_BASE_URL}
      - SPANNER_INSTANCE_ID=${SPANNER_INSTANCE_ID}
      - SPANNER_DATABASE_ID=${SPANNER_DATABASE_ID}
      - SPANNER_GRAPH_NAME=${SPANNER_GRAPH_NAME:-PolicyGraph}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME:-text-embedding-005}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME:-gemini-2.5-pro}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - FLASK_DEBUG=${FLASK_DEBUG:-false}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    volumes:
      - ./service-account-key.json:/app/service-account-key.json:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - spanner-emulator

  # Spanner emulator for local development
  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator:latest
    ports:
      - "9010:9010"
      - "9020:9020"
    environment:
      - SPANNER_EMULATOR_HOST=0.0.0.0:9010

volumes:
  logs:
    driver: local
